### ISSUE TITLE
Numeric values in `styles` apply every responsive variant

### ISSUE THREAD

**Issue by asyarb** [WalltoWall/calico#25]
See below for an example of a numeric value:

```tsx
const Example = () => <Box styles={{ zIndex: 1 }} />
```

Using a numeric value will apply classNames for every responsive variant instead of just mobile. Changing to:

```tsx
const Example = () => <Box styles={{ zIndex: "1" }} />
```

is a temporary workaround.

A likely culprit (not 100% sure) is here. 
We probably need to check for 'number' as well as 'string': 
https://github.com/WalltoWall/calico/blob/2c952efbb6c70a237c529b31f6bb4f2cb16732ec/src/utils.ts#L104-L111

**Comment by angeloashmore** [comment]
This has been fixed.
